config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reservations
  get "/signup" => "users#new"
  resources :users
  resources :reviews
  resources :rooms
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
  resources :room_images
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  belongs_to :room 
  
end

app/controllers/room_images_controller.rb
class RoomImagesController < ApplicationController
  def index
    @room_images = RoomImage.all
    render template: "room_images/index"
  end

  def new
    @room_image = RoomImage.new
    render template: "room_images/new"
  end

  def create
    @room_image = RoomImage.new(
      room_id: params[:room_image][:room_id],
      url: params[:room_image][:url],
    )
    @room_image.save
    redirect_to "/room_images"
  end

  def show
    @room_image = RoomImage.find_by(id: params[:id])
    render template: "room_images/show"
  end

  # def update
  #   @room_image = Image.find_by(id: params[:id])
  #   room_id: params[:room_image][:room_id],
  #   url: params[:room_image][:url],

  #   @room_image.save
  #   redirect_to "/room_images"
  # end

  def destroy
    @room_image = RoomImage.find_by(id: params[:id])
    @room_image.destroy
    redirect_to "/room_images", status: :see_other
  end
end

app/helpers/room_images_helper.rb
module RoomImagesHelper
end

app/views/room_images/edit.html.erb
<<h1>Edit room_image</h1>
<%= form_with model: @room_image do |form| %>
  <div>
    <%= form.label :room_id %>
    <%= form.text_field :url %>
  </div>
<% end%>

app/views/room_images/index.html.erb
<h1>All images</h1>
<% @room_images.each do |room_image| %>
  <p>room id: <%= room_image.room_id%></p>
  <p><a href="<%= room_image.url %>"><img src="<%= room_image.url %>"></a></p>
  <%= link_to "More Info", room_image %>
<% end %>
<%= link_to "New room_image", new_room_image_path %>

app/views/room_images/new.html.erb
<h1>New Image</h1>
<%= form_with model: @room_image do |form| %>
  <div>
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>
  <div>
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>
    <%= form.submit %>
  </div>
<% end%>

app/views/room_images/show.html.erb
<h1>Image info</h1>
<p>room_id: <%= @room_image.room_id%></p>
<p>url: <%= @room_image.url %></p>
<a href="/room_images">Back to all images</a>
<%= link_to "Destroy room_image", room_image_path(@room_image), data: {turbo_method: :delete} %>