config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reservations
  get "/signup" => "users#new"
  resources :users
  resources :reviews
  resources :rooms
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
  resources :room_images
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :reviews
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = current_user.reservations
    render template: "reservations/index"
  end

  def show
    @reservation = Reservation.find_by(id: params[:id])
    render template: "reservations/show"
  end

  def new
    @reservation = Reservation.new
    render template: "reservations/new"
  end

  def create
    room = Room.find_by(id: params[:reservation][:room_id])
    price = room.price
    # subtotal = (params[:end_date] - [:start_date]) * price
    # tax = 0.09 * subtotal
    # total = tax + subtotal
    total = price
    @reservation = Reservation.new(
      user_id: current_user.id,
      room_id: params[:reservation][:room_id],
      start_date: params[:reservation][:start_date],
      end_date: params[:reservation][:end_date],
      price: params[:reservation][:price],
      start_date: params[:reservation][:start_date],
      price: total,
      total_guests: params[:reservation][:total_guests],
    )
    @reservation.price = price * (@reservation.end_date - @reservation.start_date).to_i / 86400.0

    @reservation.save
    redirect_to "/reservations"
  end

  def edit
    @reservation = Reservation.find_by(id: params[:id])
    render template: "reservations/edit"
  end

  def update
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.user_id = params[:reservation][:user_id]
    @reservation.room_id = params[:reservation][:room_id]
    @reservation.start_date = params[:reservation][:start_date]
    @reservation.end_date = params[:reservation][:end_date]
    @reservation.price = params[:reservation][:price]
    @reservation.total_guests = params[:reservation][:total_guests]
    @reservation.save
    redirect_to "/reservations"
  end

  def destroy
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.destroy
    redirect_to "/reservations", status: :see_other
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
<h1>Edit reservation</h1>
<%= form_with model: @reservation do |form| %>
  <div>
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  <div>
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>
  <div>
    <%= form.label :start_date %>
    <%= form.text_field :start_date %>
  </div>
   <div>
    <%= form.label :end_date %>
    <%= form.text_field :end_date %>
  </div>
   <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
   <div>
    <%= form.label :total_guests %>
    <%= form.text_field :total_guests %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/reservations/index.html.erb
<h1>All reservations</h1>
<% @reservations.each do |reservation| %>
  <h2><%= reservation.user_id %></h2>
  <p>Room id: <%= reservation.room_id %></p>
  <p>Start date: <%= reservation.start_date %></p>
  <p>End date: <%= reservation.end_date %></p>
  <p>Price: <%= reservation.price %></p>
  <p>Total guests: <%= reservation.total_guests %></p>
   <%= link_to "More Info", reservation %>
<% end %>

<%= link_to "New reservation", new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>
<%= form_with model: @reservation do |form| %>
  <div>
    <%= form.label :room_id %>
    <%= form.collection_select :room_id, Room.all, :id, :address, include_blank: true %>
  </div>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
   <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>
   <%# <div> %>
    <%# <%= form.label :price %> 
    <%# <%= form.text_field :price %> 
  <%# </div> %>
   <div>
    <%= form.label :total_guests %>
    <%= form.text_field :total_guests %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/reservations/show.html.erb
<h1>reservation info</h1>
<h2><%= @reservation.user_id %></h2>
<p>Room Id: <%= @reservation.room_id %></p>
<p><%= @reservation.room.address %></p>
<% @reservation.room.room_images.each do |room_image| %> 
  <img src="<%= room_image.url %>">
<% end %>
<p>Start date: <%= @reservation.start_date %></p>
<p>End date: <%= @reservation.end_date %></p>
<p>Price: <%= @reservation.price %></p>
<p>Total guests: <%= @reservation.total_guests %></p>
<a href="/reservations">Back to all reservations</a>
<%= link_to "Edit reservation", edit_reservation_path(@reservation) %>
<%= link_to "Destroy reservation", reservation_path(@reservation), data: {turbo_method: :delete} %>