config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reservations
  get "/signup" => "users#new"
  resources :users
  resources :reviews
  resources :rooms
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
  resources :room_images
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :room_images
  has_many :reservations
  has_many :reviews, through: :reservations

  def is_reserved?
    [true, false].sample
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    render template: "rooms/index"
  end

  def show
    @room = Room.find_by(id: params[:id])
    render template: "rooms/show"
  end

  def new
    @room = Room.new
    render template: "rooms/new"
  end

  def create
    @room = Room.new(
      user_id: params[:room][:user_id],
      address: params[:room][:address],
      city: params[:room][:city],
      state: params[:room][:state],
      price: params[:room][:price],
      description: params[:room][:description],
      home_type: params[:room][:home_type],
      room_type: params[:room][:room_type],
      total_occupancy: params[:room][:total_occupancy],
      total_bedrooms: params[:room][:total_bedrooms],
      total_bathrooms: params[:room][:total_bathrooms],
    )
    @room.save
    redirect_to "/rooms"
  end

  def edit
    @room = Room.find_by(id: params[:id])
    render template: "rooms/edit"
  end

  def update
    @room = Room.find_by(id: params[:id])
    @room.user_id = params[:room][:user_id]
    @room.address = params[:room][:address]
    @room.city = params[:room][:city]
    @room.state = params[:room][:state]
    @room.price = params[:room][:price]
    @room.description = params[:room][:description]
    @room.home_type = params[:room][:home_type]
    @room.room_type = params[:room][:room_type]
    @room.total_occupancy = params[:room][:total_occupancy]
    @room.total_bedrooms = params[:room][:total_bedrooms]
    @room.total_bathrooms = params[:room][:total_bathrooms]
    @room.save
    redirect_to "/rooms"
  end

  def destroy
    @room = Room.find_by(id: params[:id])
    @room.destroy
    redirect_to "/rooms", status: :see_other
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>
<%= form_with model: @room do |form| %>
  <div>
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
   <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
   <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
   <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
   <div>
    <%= form.label :home_type %>
    <%= form.text_field :home_type %>
  </div>
   <div>
    <%= form.label :room_type %>
    <%= form.text_field :room_type %>
  </div>
   <div>
    <%= form.label :total_occupancy %>
    <%= form.text_field :total_occupancy %>
  </div>
   <div>
    <%= form.label :total_bedrooms %>
    <%= form.text_field :total_bedrooms %>
  </div>
   <div>
    <%= form.label :total_bathrooms %>
    <%= form.text_field :total_bathrooms %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/rooms/index.html.erb
<h1>All rooms</h1>
<% @rooms.each do |room| %>
  <h2><%= room.user_id %></h2>
  <p>Address: <%= room.address %></p>
  <p>City: <%= room.city %></p>
  <p>State: <%= room.state %></p>
  <p>Price: <%= room.price %></p>
  <p>Description: <%= room.description %></p>
  <p>Home type: <%= room.home_type %></p>
  <p>Room type: <%= room.room_type %></p>
  <p>Total occupancy: <%= room.total_occupancy %></p>
  <p>Total bedrooms: <%= room.total_bedrooms %></p>
  <p>Total bathrooms: <%= room.total_bathrooms %></p>
  <% unless room.is_reserved?%>
  <a>Reserve Room</a>
  <% end %>
  <% room.reservations.each do |reservation| %>
    <h4><%= reservation.user.name %></h4>
    <%= reservation.start_date %>
    <%= reservation.end_date %>
  <% end %>
  <%= link_to "More Info", room %>
<% end %>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>
<%= form_with model: @room do |form| %>
  <div>
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
   <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
   <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
   <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
   <div>
    <%= form.label :home_type %>
    <%= form.text_field :home_type %>
  </div>
   <div>
    <%= form.label :room_type %>
    <%= form.text_field :room_type %>
  </div>
   <div>
    <%= form.label :total_occupancy %>
    <%= form.text_field :total_occupancy %>
  </div>
   <div>
    <%= form.label :total_bedrooms %>
    <%= form.text_field :total_bedrooms %>
  </div>
   <div>
    <%= form.label :total_bathrooms %>
    <%= form.text_field :total_bathrooms %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/rooms/show.html.erb
<h1>Room info</h1>
<h2><%= @room.user_id %></h2>
<p>Address: <%= @room.address %></p>
<p>City: <%= @room.city %></p>
<p>State: <%= @room.state %></p>
<p>Price: <%= @room.price %></p>
<p>Description: <%= @room.description %></p>
<p>Home type: <%= @room.home_type %></p>
<p>Room type: <%= @room.room_type %></p>
<p>Total occupancy: <%= @room.total_occupancy %></p>
<p>Total bedrooms: <%= @room.total_bedrooms %></p>
<p>Total bathrooms: <%= @room.total_bathrooms %></p>
<a href="/rooms">Back to all rooms</a>
<%= link_to "Edit room", edit_room_path(@room) %>
<%= link_to "Destroy room", room_path(@room), data: {turbo_method: :delete} %>