config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reservations
  get "/signup" => "users#new"
  resources :users
  resources :reviews
  resources :rooms
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
  resources :room_images
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    render template: "reviews/index"
  end

  def show
    @review = Review.find_by(id: params["id"])
    render template: "reviews/show"
  end

  def new
    @review = Review.new
    render template: "reviews/new"
  end

  def create
    @review = Review.create(
      reservation_id: params[:review][:reservation_id],
      rating: params[:review][:rating],
      comment: params[:review][:comment],
    )
    if @review.valid?
      redirect_to "/reviews"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = Review.find_by(id: params[:id])
    render template: "reviews/edit"
  end

  def update
    @review = Review.find_by(id: params[:id])
    @review.reservation_id = params[:review][:reservation_id]
    @review.rating = params[:review][:rating]
    @review.comment = params[:review][:comment]
    @review.save
    redirect_to "/reviews"
  end

  def destroy
    @review = Review.find_by(id: params[:id])
    @review.destroy
    redirect_to "/reviews", status: :see_other
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/index.html.erb
<h1>All Reviews</h1>
<% @reviews.each do |review| %>
  <h2><%= review.reservation_id %></h2>
  <p>Rating: <%= review.rating %></p>
  <p>Comment: <%= review.comment %></p>
  
  <%= link_to "More Info", review %>
<% end %>
<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= form_with model: @review do |form| %>
  <div>
    <%= form.label :reservation_id %>
    <%= form.text_field :reservation_id %>
  </div>
  <div>
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>
  <div>
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/reviews/show.html.erb
<h1>Review info</h1>
<h2><%= @review.reservation_id %></h2>
<p>Rating: <%= @review.rating %></p>
<p>Comment: <%= @review.comment %></p>
<a href="/reviews">Back to all reviews</a>
<%= link_to "More Info", @review %>